{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-autoconfigure",
    "version": "3.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.0.6.jar",
          "url": "spring-boot-autoconfigure-3.0.6.jar",
          "size": 1628977,
          "sha512": "eae628a01fe009442728993309ae06b8e8507c9869446cc002e57f35b71c74caf0ee47391816497d16f972eaf03daa2c0df8b586af54685370aabd13067e7b9b",
          "sha256": "c03f1894e8d5c26cd5e1b865ed5c1fa2bd6df73f2e911edc1b6ceadba91e5cc3",
          "sha1": "8ccd83b2530c96595f92b4e07c1bb17560bfba8b",
          "md5": "7d19c54c106235fe7b496e23624afaef"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.0.6.jar",
          "url": "spring-boot-autoconfigure-3.0.6.jar",
          "size": 1628977,
          "sha512": "eae628a01fe009442728993309ae06b8e8507c9869446cc002e57f35b71c74caf0ee47391816497d16f972eaf03daa2c0df8b586af54685370aabd13067e7b9b",
          "sha256": "c03f1894e8d5c26cd5e1b865ed5c1fa2bd6df73f2e911edc1b6ceadba91e5cc3",
          "sha1": "8ccd83b2530c96595f92b4e07c1bb17560bfba8b",
          "md5": "7d19c54c106235fe7b496e23624afaef"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.0.6.jar",
          "url": "spring-boot-autoconfigure-3.0.6.jar",
          "size": 1628977,
          "sha512": "eae628a01fe009442728993309ae06b8e8507c9869446cc002e57f35b71c74caf0ee47391816497d16f972eaf03daa2c0df8b586af54685370aabd13067e7b9b",
          "sha256": "c03f1894e8d5c26cd5e1b865ed5c1fa2bd6df73f2e911edc1b6ceadba91e5cc3",
          "sha1": "8ccd83b2530c96595f92b4e07c1bb17560bfba8b",
          "md5": "7d19c54c106235fe7b496e23624afaef"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-autoconfigure-maven-optional",
          "version": "3.0.6"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.0.6.jar",
          "url": "spring-boot-autoconfigure-3.0.6.jar",
          "size": 1628977,
          "sha512": "eae628a01fe009442728993309ae06b8e8507c9869446cc002e57f35b71c74caf0ee47391816497d16f972eaf03daa2c0df8b586af54685370aabd13067e7b9b",
          "sha256": "c03f1894e8d5c26cd5e1b865ed5c1fa2bd6df73f2e911edc1b6ceadba91e5cc3",
          "sha1": "8ccd83b2530c96595f92b4e07c1bb17560bfba8b",
          "md5": "7d19c54c106235fe7b496e23624afaef"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-autoconfigure-maven-optional",
          "version": "3.0.6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.0.6-javadoc.jar",
          "url": "spring-boot-autoconfigure-3.0.6-javadoc.jar",
          "size": 2626810,
          "sha512": "de625b0ad7be0d010cd5c85dec55d1ca65925a97867ee7ecc40bd70c873a322409a9b8cd4d726dacd8ca0bdb62ca9d2b11f3b7e87e25212f9739352c57fcccea",
          "sha256": "4a22e7357d4a7c132d5fc7b1ac12bab978ff517e0accae99e388cef47f89faba",
          "sha1": "f00453b0c3c3b0cca0f95f3f1af352599a72ff1c",
          "md5": "65d56e8ebc449a76e321b6a30453685d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-autoconfigure-3.0.6-sources.jar",
          "url": "spring-boot-autoconfigure-3.0.6-sources.jar",
          "size": 966970,
          "sha512": "3b9e459b6fbd05eff52d292f6dc28202868948ae2327b05ffcb52a39d2e9ddfc179dd165ed4e142c2bf18ea0a889b8394ec316970b1811f10019d04b6dca4efa",
          "sha256": "f3f5fbdd77a4bfcd6a01a7b2eb1fcb9e5391b6df73c58607e1b83e55b929d94a",
          "sha1": "51f2e780e999f2ca52f8f4ea8bc001ba464bd1e5",
          "md5": "9976c9a68ee871ef55fef1eea8c76ba3"
        }
      ]
    }
  ]
}
