{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-buildpack-platform",
    "version": "2.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.13.4"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.23"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.7.4.jar",
          "url": "spring-boot-buildpack-platform-2.7.4.jar",
          "size": 250844,
          "sha512": "94c77608014fb4581314125fe61d4bc6e27c91c1feba6a408eaba5c90c62f921553ab4237c2fae70ce446c87ff3fc4023e37a1c6018dd3c5cfebde35b0a55f21",
          "sha256": "81ea940bde7e9f368ee7a60a80914d731394315bab40bc113702ef5a9ff71804",
          "sha1": "0abee4a9e8b23af78a8ecff6759756c8acb62dda",
          "md5": "189f6c1d4df0728d3b497659ceb5f714"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.13.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.13.4"
          }
        },
        {
          "group": "net.java.dev.jna",
          "module": "jna-platform",
          "version": {
            "requires": "5.7.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.23"
          }
        },
        {
          "group": "org.tomlj",
          "module": "tomlj",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.7.4.jar",
          "url": "spring-boot-buildpack-platform-2.7.4.jar",
          "size": 250844,
          "sha512": "94c77608014fb4581314125fe61d4bc6e27c91c1feba6a408eaba5c90c62f921553ab4237c2fae70ce446c87ff3fc4023e37a1c6018dd3c5cfebde35b0a55f21",
          "sha256": "81ea940bde7e9f368ee7a60a80914d731394315bab40bc113702ef5a9ff71804",
          "sha1": "0abee4a9e8b23af78a8ecff6759756c8acb62dda",
          "md5": "189f6c1d4df0728d3b497659ceb5f714"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.7.4-javadoc.jar",
          "url": "spring-boot-buildpack-platform-2.7.4-javadoc.jar",
          "size": 302667,
          "sha512": "9b47d4557e87faec175d9531637600fcbdb52b364ad42dfca33c9d8a45f7fe21f89272d4804ead5ba7f42633d7e947452c6a3f59ce231399a8681ef295da1668",
          "sha256": "6489334e90378a588bc3c359978095785a5e461a217d9ab7aed30e2b9bf1b81f",
          "sha1": "e67813d0a45788ace71413bdcf04bda188802832",
          "md5": "4fe28a5518ed7133d1d432c1d4b4bd38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.7.4-sources.jar",
          "url": "spring-boot-buildpack-platform-2.7.4-sources.jar",
          "size": 161323,
          "sha512": "efc932f78cc3cbfadace9a8d5474f3ae36cff62ea38d28039a276a36e11e70f99938aa82d2c76ff13cc43d4b3993ade9f2af886b755c8157077c51c642624e63",
          "sha256": "208a011c25c73afd6c6999b7924b74b83c8615f806705ba123bf358633185255",
          "sha1": "a2a2bda9197ea4a0b29dde12f0b89e3928879f60",
          "md5": "48dc71f429ca859ba29220460c939347"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.7.4.jar",
          "url": "spring-boot-buildpack-platform-2.7.4.jar",
          "size": 250844,
          "sha512": "94c77608014fb4581314125fe61d4bc6e27c91c1feba6a408eaba5c90c62f921553ab4237c2fae70ce446c87ff3fc4023e37a1c6018dd3c5cfebde35b0a55f21",
          "sha256": "81ea940bde7e9f368ee7a60a80914d731394315bab40bc113702ef5a9ff71804",
          "sha1": "0abee4a9e8b23af78a8ecff6759756c8acb62dda",
          "md5": "189f6c1d4df0728d3b497659ceb5f714"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-buildpack-platform-maven-optional",
          "version": "2.7.4"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-buildpack-platform-2.7.4.jar",
          "url": "spring-boot-buildpack-platform-2.7.4.jar",
          "size": 250844,
          "sha512": "94c77608014fb4581314125fe61d4bc6e27c91c1feba6a408eaba5c90c62f921553ab4237c2fae70ce446c87ff3fc4023e37a1c6018dd3c5cfebde35b0a55f21",
          "sha256": "81ea940bde7e9f368ee7a60a80914d731394315bab40bc113702ef5a9ff71804",
          "sha1": "0abee4a9e8b23af78a8ecff6759756c8acb62dda",
          "md5": "189f6c1d4df0728d3b497659ceb5f714"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-buildpack-platform-maven-optional",
          "version": "2.7.4"
        }
      ]
    }
  ]
}
