{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot",
    "version": "2.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.23"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.23"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-2.7.4.jar",
          "url": "spring-boot-2.7.4.jar",
          "size": 1448948,
          "sha512": "d706427d60558181a720d4144dd91b496c517fad8d2ad347b6b1622bbf6d365d0554b1d6d55deeee6cdcd01bf654e014e09f593db584cd1c5b8f41dcbd9918b7",
          "sha256": "c5e8f1f7ecb93e8452c3c0d58838f7fb74853ad117f50e592c69dfca4fe6cc89",
          "sha1": "8a6aeb18645a6191dc957b023907f8511dabffd1",
          "md5": "f2ff3fe8fa3275cd1687cdfd7055a208"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.23"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "5.3.23"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-2.7.4.jar",
          "url": "spring-boot-2.7.4.jar",
          "size": 1448948,
          "sha512": "d706427d60558181a720d4144dd91b496c517fad8d2ad347b6b1622bbf6d365d0554b1d6d55deeee6cdcd01bf654e014e09f593db584cd1c5b8f41dcbd9918b7",
          "sha256": "c5e8f1f7ecb93e8452c3c0d58838f7fb74853ad117f50e592c69dfca4fe6cc89",
          "sha1": "8a6aeb18645a6191dc957b023907f8511dabffd1",
          "md5": "f2ff3fe8fa3275cd1687cdfd7055a208"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-2.7.4-javadoc.jar",
          "url": "spring-boot-2.7.4-javadoc.jar",
          "size": 2036352,
          "sha512": "5f0ed3bc3a273481636db572d1cff0296c346760b2a170ec5db8e933448f246c913a29534cf219a73d988f18a47488db8f76d7606001a490b5750c2bceca2f1c",
          "sha256": "7aa6b830a8b58423d209c18eae9c0b778c9ad34e4e92eea65ed5ad66314a1aac",
          "sha1": "7a1794fcfc881cf0dd4c5f3e52e0f3f271019930",
          "md5": "47d8ea4f22d529369e37110b817d0089"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-2.7.4-sources.jar",
          "url": "spring-boot-2.7.4-sources.jar",
          "size": 1019991,
          "sha512": "ff29719093e42374c840cfbb290eb955e1d24d002620b6eb9191134857b4c94b1e63e066be628dc1cd3adef87b3c3b59f16297a5d15bd2463a578ab4283a140b",
          "sha256": "b57b70c5f9a0ad3bfce057f390b61c00f3ed5f7c71830ac149507f9189c1a788",
          "sha1": "d2005285f65aac2452ef5c5da3a0f9346808ed90",
          "md5": "3e9db2883f888b5dd6dc3014012d5b81"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-2.7.4.jar",
          "url": "spring-boot-2.7.4.jar",
          "size": 1448948,
          "sha512": "d706427d60558181a720d4144dd91b496c517fad8d2ad347b6b1622bbf6d365d0554b1d6d55deeee6cdcd01bf654e014e09f593db584cd1c5b8f41dcbd9918b7",
          "sha256": "c5e8f1f7ecb93e8452c3c0d58838f7fb74853ad117f50e592c69dfca4fe6cc89",
          "sha1": "8a6aeb18645a6191dc957b023907f8511dabffd1",
          "md5": "f2ff3fe8fa3275cd1687cdfd7055a208"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-maven-optional",
          "version": "2.7.4"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-2.7.4.jar",
          "url": "spring-boot-2.7.4.jar",
          "size": 1448948,
          "sha512": "d706427d60558181a720d4144dd91b496c517fad8d2ad347b6b1622bbf6d365d0554b1d6d55deeee6cdcd01bf654e014e09f593db584cd1c5b8f41dcbd9918b7",
          "sha256": "c5e8f1f7ecb93e8452c3c0d58838f7fb74853ad117f50e592c69dfca4fe6cc89",
          "sha1": "8a6aeb18645a6191dc957b023907f8511dabffd1",
          "md5": "f2ff3fe8fa3275cd1687cdfd7055a208"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-maven-optional",
          "version": "2.7.4"
        }
      ]
    }
  ]
}
