{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.65"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.65"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.65"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.4.jar",
          "url": "spring-boot-starter-tomcat-2.7.4.jar",
          "size": 4796,
          "sha512": "40515f22b142a761a8612bf131435b4a89d23c42c6fda6104ea9481e5802bc03982b8527a46a3ea085a06875d84f745eb1ebb2d15cf8b32c5805d76cc0d808a3",
          "sha256": "9b09224692100eca47e368b130c7aaa9db4ea78b741d0cc40187e09c6b6b6d41",
          "sha1": "b49555d2bfea184089f8e6b8b338faa5bc9ad254",
          "md5": "d1c8ec78ca3b406e422cb4990a402f0d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.65"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.65"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.65"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.4.jar",
          "url": "spring-boot-starter-tomcat-2.7.4.jar",
          "size": 4796,
          "sha512": "40515f22b142a761a8612bf131435b4a89d23c42c6fda6104ea9481e5802bc03982b8527a46a3ea085a06875d84f745eb1ebb2d15cf8b32c5805d76cc0d808a3",
          "sha256": "9b09224692100eca47e368b130c7aaa9db4ea78b741d0cc40187e09c6b6b6d41",
          "sha1": "b49555d2bfea184089f8e6b8b338faa5bc9ad254",
          "md5": "d1c8ec78ca3b406e422cb4990a402f0d"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.4.jar",
          "url": "spring-boot-starter-tomcat-2.7.4.jar",
          "size": 4796,
          "sha512": "40515f22b142a761a8612bf131435b4a89d23c42c6fda6104ea9481e5802bc03982b8527a46a3ea085a06875d84f745eb1ebb2d15cf8b32c5805d76cc0d808a3",
          "sha256": "9b09224692100eca47e368b130c7aaa9db4ea78b741d0cc40187e09c6b6b6d41",
          "sha1": "b49555d2bfea184089f8e6b8b338faa5bc9ad254",
          "md5": "d1c8ec78ca3b406e422cb4990a402f0d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.7.4"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.4.jar",
          "url": "spring-boot-starter-tomcat-2.7.4.jar",
          "size": 4796,
          "sha512": "40515f22b142a761a8612bf131435b4a89d23c42c6fda6104ea9481e5802bc03982b8527a46a3ea085a06875d84f745eb1ebb2d15cf8b32c5805d76cc0d808a3",
          "sha256": "9b09224692100eca47e368b130c7aaa9db4ea78b741d0cc40187e09c6b6b6d41",
          "sha1": "b49555d2bfea184089f8e6b8b338faa5bc9ad254",
          "md5": "d1c8ec78ca3b406e422cb4990a402f0d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.7.4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.4-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.7.4-javadoc.jar",
          "size": 4744,
          "sha512": "41c1d7120136029940df132cfa28845f740040c7c0281b3b776d677bc8c8ef22a69341fc9b50537273e27b8e5a071a2a88488a0ae1ef37ff7ac34957b3e2ee43",
          "sha256": "be828e6d1dec1af5c1bcbe2e0cf91de2e6a155da5a14d32fffdce464fa9716e1",
          "sha1": "a4b7d35067cd2f45812adb4b762f3f0be76e5ba3",
          "md5": "02bb72ffa8e4907319e7e5e74b84541d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.4-sources.jar",
          "url": "spring-boot-starter-tomcat-2.7.4-sources.jar",
          "size": 4743,
          "sha512": "a1736854fed0db7c13a098f6c5f63d937884fcf4cde98b9b134d58b8fe36e36b00533ccbaba61b067f62fa3c30dd7dd585c2548aca811db30de7fde95cc0fbc8",
          "sha256": "672c000c7d00c5bd898e911974b58b539b8e0c22f7d6ccac796907bfd0e18f57",
          "sha1": "60e864b5b00175f688d11b148a6fd751a7086151",
          "md5": "bdc43a8f9a2c0deab7057e1915b2ee38"
        }
      ]
    }
  ]
}
