{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.23"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.7.4.jar",
          "url": "spring-boot-starter-2.7.4.jar",
          "size": 4770,
          "sha512": "12b17fffe793e506e027447867196aafb14ae5a2651fd7b5cb5fa562e891e76eff2ad9ad5aa734e8dd385f3d119c81407a0e455a7ff986886563ab415c156e1b",
          "sha256": "09d22caeb829fa65a98dbcb38373db5a15fc3a3afe9548a5389db86aa27ca224",
          "sha1": "5fe2fed415877251263ebfac15efde59b1ea5913",
          "md5": "d9558a7e7a71d5bad465e3e151b31590"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.23"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.30"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.7.4.jar",
          "url": "spring-boot-starter-2.7.4.jar",
          "size": 4770,
          "sha512": "12b17fffe793e506e027447867196aafb14ae5a2651fd7b5cb5fa562e891e76eff2ad9ad5aa734e8dd385f3d119c81407a0e455a7ff986886563ab415c156e1b",
          "sha256": "09d22caeb829fa65a98dbcb38373db5a15fc3a3afe9548a5389db86aa27ca224",
          "sha1": "5fe2fed415877251263ebfac15efde59b1ea5913",
          "md5": "d9558a7e7a71d5bad465e3e151b31590"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.4.jar",
          "url": "spring-boot-starter-2.7.4.jar",
          "size": 4770,
          "sha512": "12b17fffe793e506e027447867196aafb14ae5a2651fd7b5cb5fa562e891e76eff2ad9ad5aa734e8dd385f3d119c81407a0e455a7ff986886563ab415c156e1b",
          "sha256": "09d22caeb829fa65a98dbcb38373db5a15fc3a3afe9548a5389db86aa27ca224",
          "sha1": "5fe2fed415877251263ebfac15efde59b1ea5913",
          "md5": "d9558a7e7a71d5bad465e3e151b31590"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.7.4"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.4.jar",
          "url": "spring-boot-starter-2.7.4.jar",
          "size": 4770,
          "sha512": "12b17fffe793e506e027447867196aafb14ae5a2651fd7b5cb5fa562e891e76eff2ad9ad5aa734e8dd385f3d119c81407a0e455a7ff986886563ab415c156e1b",
          "sha256": "09d22caeb829fa65a98dbcb38373db5a15fc3a3afe9548a5389db86aa27ca224",
          "sha1": "5fe2fed415877251263ebfac15efde59b1ea5913",
          "md5": "d9558a7e7a71d5bad465e3e151b31590"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.7.4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.4-javadoc.jar",
          "url": "spring-boot-starter-2.7.4-javadoc.jar",
          "size": 4738,
          "sha512": "4d342ad2fad1bed4025616826ad0d4bcb4709dcf1e9a54ea2bcc6e28bc916ccec472f1bd5265f07e7e6c86996e82e16d59291fa6a55ff42af438a67a650161ba",
          "sha256": "5f308ba2cf6a756a79d362e822525ff43e7626ed54e0577f07e63e3f09934b46",
          "sha1": "474ed94c84124f4e72d8993aa10590c8f7b0a28b",
          "md5": "40ffb4eefd26cfa7754dc65f6559ac62"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.7.4-sources.jar",
          "url": "spring-boot-starter-2.7.4-sources.jar",
          "size": 4737,
          "sha512": "c7abf71c6c6f505c2c87add583dfa5ac63766166773faafdd8137e4aac924bcfb5a70208c7c51cda5a4d0519778ade9206d9d14414c27b26e71cd3d3f0c11d88",
          "sha256": "a1cde1aff6f8ba6971ee92a63c62e7017a52ecd3623601cc757d80c0e19e6a9a",
          "sha1": "0d3025e70090dda5f8aa73e7f46548ca4a5db39d",
          "md5": "9168a36b6f1cb6940718fbe6009f0dcb"
        }
      ]
    }
  ]
}
