{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-web",
    "version": "3.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.0.6.jar",
          "url": "spring-boot-starter-web-3.0.6.jar",
          "size": 4804,
          "sha512": "485a270af8854e371084cbb220fd08edbbb143110c0faf2ae8a273ad4984e9404a62c512b0553c9feeefaee67fdb97df7f9b5787d69dde23b3d5fe7b9aaab4a4",
          "sha256": "df2f6e34da4efc477730c815130cdb6ce112e1ed4c7ee6d9a2a710148f0d63d2",
          "sha1": "7c6597cae584c359d7e4ddea6e006176e0c15936",
          "md5": "6c366f532b8ea549c409acb29409419b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-json",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-tomcat",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-webmvc",
          "version": {
            "requires": "6.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-web-3.0.6.jar",
          "url": "spring-boot-starter-web-3.0.6.jar",
          "size": 4804,
          "sha512": "485a270af8854e371084cbb220fd08edbbb143110c0faf2ae8a273ad4984e9404a62c512b0553c9feeefaee67fdb97df7f9b5787d69dde23b3d5fe7b9aaab4a4",
          "sha256": "df2f6e34da4efc477730c815130cdb6ce112e1ed4c7ee6d9a2a710148f0d63d2",
          "sha1": "7c6597cae584c359d7e4ddea6e006176e0c15936",
          "md5": "6c366f532b8ea549c409acb29409419b"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.0.6.jar",
          "url": "spring-boot-starter-web-3.0.6.jar",
          "size": 4804,
          "sha512": "485a270af8854e371084cbb220fd08edbbb143110c0faf2ae8a273ad4984e9404a62c512b0553c9feeefaee67fdb97df7f9b5787d69dde23b3d5fe7b9aaab4a4",
          "sha256": "df2f6e34da4efc477730c815130cdb6ce112e1ed4c7ee6d9a2a710148f0d63d2",
          "sha1": "7c6597cae584c359d7e4ddea6e006176e0c15936",
          "md5": "6c366f532b8ea549c409acb29409419b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "3.0.6"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.0.6.jar",
          "url": "spring-boot-starter-web-3.0.6.jar",
          "size": 4804,
          "sha512": "485a270af8854e371084cbb220fd08edbbb143110c0faf2ae8a273ad4984e9404a62c512b0553c9feeefaee67fdb97df7f9b5787d69dde23b3d5fe7b9aaab4a4",
          "sha256": "df2f6e34da4efc477730c815130cdb6ce112e1ed4c7ee6d9a2a710148f0d63d2",
          "sha1": "7c6597cae584c359d7e4ddea6e006176e0c15936",
          "md5": "6c366f532b8ea549c409acb29409419b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-web-maven-optional",
          "version": "3.0.6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.0.6-javadoc.jar",
          "url": "spring-boot-starter-web-3.0.6-javadoc.jar",
          "size": 4742,
          "sha512": "38ba757e368a8a048b16b9ea02b06c9aa027292e88fbf1c9f6e55984ca76f80d0a215364cfd3aaea2744b0580791606519bbea49fa2d77dcebcf11ed487919e4",
          "sha256": "2f5dba6c9c141b1243a04803bd82400d89a517f25ab376661aabe38e7efcc498",
          "sha1": "ae06bf8f86368c50e6219299583a002dcb066b4d",
          "md5": "f889bfbb2f8aa8714c9ea93c00cfda53"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-web-3.0.6-sources.jar",
          "url": "spring-boot-starter-web-3.0.6-sources.jar",
          "size": 4741,
          "sha512": "6fab4bd00301e40f3cdfd62f9cb04384c1a061b53711789d5a2d25670e3716de38165cb55aaefc512f4ab0bbf6d09b819648b291438812c7647f0d35ad75eedc",
          "sha256": "f401d314723f67a028fa10512b0bb56695bb519990a2ac5f0b0d954d32a17fd0",
          "sha1": "6ca12f62bb22ef602a532dfc17602bc1182701e4",
          "md5": "d5fd37a44a232b7f88d7ad680363b033"
        }
      ]
    }
  ]
}
