{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-test",
    "version": "2.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.8.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.23"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.23"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.7.4.jar",
          "url": "spring-boot-starter-test-2.7.4.jar",
          "size": 4792,
          "sha512": "68a7740d38d4b6b98251e7ab5540ebc5fa5714c306cda13bc5e3351a8fe81bc6bf766d48aa7c17f6a333e8aab6978292b4f010a2b91492a545a3e871ede347e6",
          "sha256": "25834f36625349f674ce0608f493b7457f7d73adc79f1dc0e4c786a07bd57962",
          "sha1": "6ffe636eb08825712c6ea24d2351888eaf626485",
          "md5": "3cd98390a32f0cc73d0f4bafe457b134"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-test-autoconfigure",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "com.jayway.jsonpath",
          "module": "json-path",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "jakarta.xml.bind",
          "module": "jakarta.xml.bind-api",
          "version": {
            "requires": "2.3.3"
          }
        },
        {
          "group": "org.assertj",
          "module": "assertj-core",
          "version": {
            "requires": "3.22.0"
          }
        },
        {
          "group": "org.hamcrest",
          "module": "hamcrest",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter",
          "version": {
            "requires": "5.8.2"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-core",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "org.mockito",
          "module": "mockito-junit-jupiter",
          "version": {
            "requires": "4.5.1"
          }
        },
        {
          "group": "org.skyscreamer",
          "module": "jsonassert",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.23"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "5.3.23"
          }
        },
        {
          "group": "org.xmlunit",
          "module": "xmlunit-core",
          "version": {
            "requires": "2.9.0"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-test-2.7.4.jar",
          "url": "spring-boot-starter-test-2.7.4.jar",
          "size": 4792,
          "sha512": "68a7740d38d4b6b98251e7ab5540ebc5fa5714c306cda13bc5e3351a8fe81bc6bf766d48aa7c17f6a333e8aab6978292b4f010a2b91492a545a3e871ede347e6",
          "sha256": "25834f36625349f674ce0608f493b7457f7d73adc79f1dc0e4c786a07bd57962",
          "sha1": "6ffe636eb08825712c6ea24d2351888eaf626485",
          "md5": "3cd98390a32f0cc73d0f4bafe457b134"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.7.4.jar",
          "url": "spring-boot-starter-test-2.7.4.jar",
          "size": 4792,
          "sha512": "68a7740d38d4b6b98251e7ab5540ebc5fa5714c306cda13bc5e3351a8fe81bc6bf766d48aa7c17f6a333e8aab6978292b4f010a2b91492a545a3e871ede347e6",
          "sha256": "25834f36625349f674ce0608f493b7457f7d73adc79f1dc0e4c786a07bd57962",
          "sha1": "6ffe636eb08825712c6ea24d2351888eaf626485",
          "md5": "3cd98390a32f0cc73d0f4bafe457b134"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-test-maven-optional",
          "version": "2.7.4"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.7.4.jar",
          "url": "spring-boot-starter-test-2.7.4.jar",
          "size": 4792,
          "sha512": "68a7740d38d4b6b98251e7ab5540ebc5fa5714c306cda13bc5e3351a8fe81bc6bf766d48aa7c17f6a333e8aab6978292b4f010a2b91492a545a3e871ede347e6",
          "sha256": "25834f36625349f674ce0608f493b7457f7d73adc79f1dc0e4c786a07bd57962",
          "sha1": "6ffe636eb08825712c6ea24d2351888eaf626485",
          "md5": "3cd98390a32f0cc73d0f4bafe457b134"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-test-maven-optional",
          "version": "2.7.4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.7.4-javadoc.jar",
          "url": "spring-boot-starter-test-2.7.4-javadoc.jar",
          "size": 4743,
          "sha512": "f26946a28fb220e6681d3c7b45ccc6bed8ba54ef10a15901a3603099cb3aa02d7a815944687f9a98cb3d06e7907ff671cbd20c3c30c70d9f23753a0f62357f52",
          "sha256": "85986dfb2447a130dad73740cb0edc0b2d18f9d6ebf0654d5b27d09e675cacd2",
          "sha1": "eae10c1bbd36b90d83707f031af5f934d0dcfa48",
          "md5": "5f76c59c439a3c37a9817ee2be46957e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-test-2.7.4-sources.jar",
          "url": "spring-boot-starter-test-2.7.4-sources.jar",
          "size": 4741,
          "sha512": "c4f66b6697148d71a876bb05b6b6e250cdc27f3fa0c633ca132a2a1073480692b89757dfbf6c7996e3574e6aa3280c859ed78854caf1415c7f395e31fc895f54",
          "sha256": "0f3a30aa7544d7ef8999c207153442ef30c6b46dc8396a6d36d51ab3ec0c7009",
          "sha1": "da315794158d7d5a5051c219dc195dbd31089bd8",
          "md5": "eaaa755e567da48b5c3042f23e9064d4"
        }
      ]
    }
  ]
}
