{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-loader-tools",
    "version": "3.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.6.jar",
          "url": "spring-boot-loader-tools-3.0.6.jar",
          "size": 250657,
          "sha512": "5eab53eced90b95177364eeda8817b6094d5924f2f6a979e849fd1b24e682caeff942d909e03350d3ebeea596e76fa475ee96c15050c4ac37961eaabb9369251",
          "sha256": "5798ec1c671d123936d42b56bc8d02353a697464b014e083547433e75089aef3",
          "sha1": "99da2303c1cee73d68eff5d261b04ef30bf00371",
          "md5": "de60c64beb91dad20f195176b0ccf69d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.6.jar",
          "url": "spring-boot-loader-tools-3.0.6.jar",
          "size": 250657,
          "sha512": "5eab53eced90b95177364eeda8817b6094d5924f2f6a979e849fd1b24e682caeff942d909e03350d3ebeea596e76fa475ee96c15050c4ac37961eaabb9369251",
          "sha256": "5798ec1c671d123936d42b56bc8d02353a697464b014e083547433e75089aef3",
          "sha1": "99da2303c1cee73d68eff5d261b04ef30bf00371",
          "md5": "de60c64beb91dad20f195176b0ccf69d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.6-javadoc.jar",
          "url": "spring-boot-loader-tools-3.0.6-javadoc.jar",
          "size": 245768,
          "sha512": "bd15cbfb81b614e1cd4bfb98c2ed2b9db841dba95fc15f26c1a10d71b8c77a29fd289c9becb722041c74ef897943172e09b95b6d6a4e9f928bd60af82cb87e6e",
          "sha256": "6a0ed6f3fe68228f7fa3d15d15df66293473993f1c223cae657f0cebec35b43e",
          "sha1": "2d380ff4afc5209ffe4de002f4b22cb79008eae3",
          "md5": "2f0c50807b9da277335d234a85d731c9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.6-sources.jar",
          "url": "spring-boot-loader-tools-3.0.6-sources.jar",
          "size": 73276,
          "sha512": "bb86444b743418fffa42e17fea580e5d6c8a56abfa78a0a2783ad858da71fec301ba5186c7afe3389e4cdb1614fdb69b54ed5f4ce57751b09ae18111098c782a",
          "sha256": "fddaadb1f8942db06d6da7eba716ba26cba34b3fede44896996401dd44fdd001",
          "sha1": "7ec8c64015ad3f527537423ab82e73108c201e84",
          "md5": "585bab554fd31dade0a11a724423620e"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.6.jar",
          "url": "spring-boot-loader-tools-3.0.6.jar",
          "size": 250657,
          "sha512": "5eab53eced90b95177364eeda8817b6094d5924f2f6a979e849fd1b24e682caeff942d909e03350d3ebeea596e76fa475ee96c15050c4ac37961eaabb9369251",
          "sha256": "5798ec1c671d123936d42b56bc8d02353a697464b014e083547433e75089aef3",
          "sha1": "99da2303c1cee73d68eff5d261b04ef30bf00371",
          "md5": "de60c64beb91dad20f195176b0ccf69d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-loader-tools-maven-optional",
          "version": "3.0.6"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-loader-tools-3.0.6.jar",
          "url": "spring-boot-loader-tools-3.0.6.jar",
          "size": 250657,
          "sha512": "5eab53eced90b95177364eeda8817b6094d5924f2f6a979e849fd1b24e682caeff942d909e03350d3ebeea596e76fa475ee96c15050c4ac37961eaabb9369251",
          "sha256": "5798ec1c671d123936d42b56bc8d02353a697464b014e083547433e75089aef3",
          "sha1": "99da2303c1cee73d68eff5d261b04ef30bf00371",
          "md5": "de60c64beb91dad20f195176b0ccf69d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-loader-tools-maven-optional",
          "version": "3.0.6"
        }
      ]
    }
  ]
}
