{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-gradle-plugin",
    "version": "2.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.7.4.jar",
          "url": "spring-boot-gradle-plugin-2.7.4.jar",
          "size": 124599,
          "sha512": "6bb0b32a065d1f745299fc5a60c5f3cf7cea027e267f1f3cea6de4d09abcecc7c223cf78f3cdf3f6afa57dabb81813cef0547217b08b18069f399b461146f283",
          "sha256": "bdd788ed0230feb0a8e51004cd7116334d39da8f34504e469f7b1d1ffdf21f25",
          "sha1": "7a5b8919885c8c3b43885a495a6a071292d54be6",
          "md5": "456eb87b75222f3b4a4b35fbbf0bee63"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-buildpack-platform",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-loader-tools",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.0.14.RELEASE"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.23"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.7.4.jar",
          "url": "spring-boot-gradle-plugin-2.7.4.jar",
          "size": 124599,
          "sha512": "6bb0b32a065d1f745299fc5a60c5f3cf7cea027e267f1f3cea6de4d09abcecc7c223cf78f3cdf3f6afa57dabb81813cef0547217b08b18069f399b461146f283",
          "sha256": "bdd788ed0230feb0a8e51004cd7116334d39da8f34504e469f7b1d1ffdf21f25",
          "sha1": "7a5b8919885c8c3b43885a495a6a071292d54be6",
          "md5": "456eb87b75222f3b4a4b35fbbf0bee63"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.7.4-javadoc.jar",
          "url": "spring-boot-gradle-plugin-2.7.4-javadoc.jar",
          "size": 241844,
          "sha512": "fbb718cb6dfbbeb533a8fe20f825ca5a0447aa87931330eda043f8efc2dfef6e3f0edbf6069107824efc9eae0153901a3bbf3767414b2f076690cb14147bb409",
          "sha256": "47a6452570aa61dd613a8d8901b3614ec4a0b713a59b6f31ad5dfe1c868e3999",
          "sha1": "bc65995d4c4d7488726584a1073734e603d121d4",
          "md5": "e175452c0c82b9422ff81ba0027f7a7c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.7.4-sources.jar",
          "url": "spring-boot-gradle-plugin-2.7.4-sources.jar",
          "size": 71990,
          "sha512": "ff2a27199a38b1a062dbe5eafe9460c6ff248ba32e77a1ef12e8325bc876a515139fd2c48bf758e80c3d17c45fa467c420fa272426b03a5f9a4e2405f56b5751",
          "sha256": "f2db8cf42d38a76bd00f38ff35ecd021b4e9749a7fa163056451f788f1c00d6c",
          "sha1": "96feba81bd193e489de7e79948aa24673c9ca49c",
          "md5": "a9a662ed8f815b4e77734683a6e20482"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.7.4.jar",
          "url": "spring-boot-gradle-plugin-2.7.4.jar",
          "size": 124599,
          "sha512": "6bb0b32a065d1f745299fc5a60c5f3cf7cea027e267f1f3cea6de4d09abcecc7c223cf78f3cdf3f6afa57dabb81813cef0547217b08b18069f399b461146f283",
          "sha256": "bdd788ed0230feb0a8e51004cd7116334d39da8f34504e469f7b1d1ffdf21f25",
          "sha1": "7a5b8919885c8c3b43885a495a6a071292d54be6",
          "md5": "456eb87b75222f3b4a4b35fbbf0bee63"
        },
        {
          "name": "spring-boot-gradle-plugin-2.7.4.jar",
          "url": "spring-boot-gradle-plugin-2.7.4.jar",
          "size": 124599,
          "sha512": "6bb0b32a065d1f745299fc5a60c5f3cf7cea027e267f1f3cea6de4d09abcecc7c223cf78f3cdf3f6afa57dabb81813cef0547217b08b18069f399b461146f283",
          "sha256": "bdd788ed0230feb0a8e51004cd7116334d39da8f34504e469f7b1d1ffdf21f25",
          "sha1": "7a5b8919885c8c3b43885a495a6a071292d54be6",
          "md5": "456eb87b75222f3b4a4b35fbbf0bee63"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-gradle-plugin-maven-optional",
          "version": "2.7.4"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-2.7.4.jar",
          "url": "spring-boot-gradle-plugin-2.7.4.jar",
          "size": 124599,
          "sha512": "6bb0b32a065d1f745299fc5a60c5f3cf7cea027e267f1f3cea6de4d09abcecc7c223cf78f3cdf3f6afa57dabb81813cef0547217b08b18069f399b461146f283",
          "sha256": "bdd788ed0230feb0a8e51004cd7116334d39da8f34504e469f7b1d1ffdf21f25",
          "sha1": "7a5b8919885c8c3b43885a495a6a071292d54be6",
          "md5": "456eb87b75222f3b4a4b35fbbf0bee63"
        },
        {
          "name": "spring-boot-gradle-plugin-2.7.4.jar",
          "url": "spring-boot-gradle-plugin-2.7.4.jar",
          "size": 124599,
          "sha512": "6bb0b32a065d1f745299fc5a60c5f3cf7cea027e267f1f3cea6de4d09abcecc7c223cf78f3cdf3f6afa57dabb81813cef0547217b08b18069f399b461146f283",
          "sha256": "bdd788ed0230feb0a8e51004cd7116334d39da8f34504e469f7b1d1ffdf21f25",
          "sha1": "7a5b8919885c8c3b43885a495a6a071292d54be6",
          "md5": "456eb87b75222f3b4a4b35fbbf0bee63"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-gradle-plugin-maven-optional",
          "version": "2.7.4"
        }
      ]
    }
  ]
}
