{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-gradle-plugin",
    "version": "3.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.0.6.jar",
          "url": "spring-boot-gradle-plugin-3.0.6.jar",
          "size": 137490,
          "sha512": "17bd04e8e018b2eb03c584ea39f5dc1a08cb64723e9abca6c9eed2e6e2b554aa4267f923440ff37f361fea178b021cfe53b725d67d3b6139f38e300b4bef0a65",
          "sha256": "b4e5bef914a220c1af37e7b5d957481125237e47fd83e91309740fb0c018351d",
          "sha1": "2ddef8d6a039aa16d3a59949ad784d541baa7d72",
          "md5": "7c1e60f06f907c9ae31b18bd2344cc07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-buildpack-platform",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-loader-tools",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "io.spring.gradle",
          "module": "dependency-management-plugin",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-compress",
          "version": {
            "requires": "1.21"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.0.6.jar",
          "url": "spring-boot-gradle-plugin-3.0.6.jar",
          "size": 137490,
          "sha512": "17bd04e8e018b2eb03c584ea39f5dc1a08cb64723e9abca6c9eed2e6e2b554aa4267f923440ff37f361fea178b021cfe53b725d67d3b6139f38e300b4bef0a65",
          "sha256": "b4e5bef914a220c1af37e7b5d957481125237e47fd83e91309740fb0c018351d",
          "sha1": "2ddef8d6a039aa16d3a59949ad784d541baa7d72",
          "md5": "7c1e60f06f907c9ae31b18bd2344cc07"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.0.6-javadoc.jar",
          "url": "spring-boot-gradle-plugin-3.0.6-javadoc.jar",
          "size": 310545,
          "sha512": "3c451983363879a0b140853580024730e906bfb3f5c083b1ce0b08781c5e1a701418283a02d5eb6e0600ff206e1d5373c82593d45cafde791990e9e7327a005f",
          "sha256": "50cb2056613f970fdfb0a19709eae9b8a6a0cbf48be00fb236b3134fecc0849a",
          "sha1": "328ac044f204348938daef392db5283c4d8dcb52",
          "md5": "8b1db07904b11e3d67747c1a60995d17"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.0.6-sources.jar",
          "url": "spring-boot-gradle-plugin-3.0.6-sources.jar",
          "size": 78750,
          "sha512": "ebfc69dae9e9c2f5b965ef4a7b86cfd4106c8a96b289f52618d11a06274b46dea60084e3b07c875addc9fc2999af7850c3a1838aff48dd91cb0a14cc3f4b2a7f",
          "sha256": "d8ea0affefd05f44814b1990d04503995c428663f37f18a556eff782c2fcee13",
          "sha1": "7b418710778ba3ce0b0fd9af24d6870c4900dbfe",
          "md5": "00cbf2cd2f9c8751f70af71f73ed6daf"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.0.6.jar",
          "url": "spring-boot-gradle-plugin-3.0.6.jar",
          "size": 137490,
          "sha512": "17bd04e8e018b2eb03c584ea39f5dc1a08cb64723e9abca6c9eed2e6e2b554aa4267f923440ff37f361fea178b021cfe53b725d67d3b6139f38e300b4bef0a65",
          "sha256": "b4e5bef914a220c1af37e7b5d957481125237e47fd83e91309740fb0c018351d",
          "sha1": "2ddef8d6a039aa16d3a59949ad784d541baa7d72",
          "md5": "7c1e60f06f907c9ae31b18bd2344cc07"
        },
        {
          "name": "spring-boot-gradle-plugin-3.0.6.jar",
          "url": "spring-boot-gradle-plugin-3.0.6.jar",
          "size": 137490,
          "sha512": "17bd04e8e018b2eb03c584ea39f5dc1a08cb64723e9abca6c9eed2e6e2b554aa4267f923440ff37f361fea178b021cfe53b725d67d3b6139f38e300b4bef0a65",
          "sha256": "b4e5bef914a220c1af37e7b5d957481125237e47fd83e91309740fb0c018351d",
          "sha1": "2ddef8d6a039aa16d3a59949ad784d541baa7d72",
          "md5": "7c1e60f06f907c9ae31b18bd2344cc07"
        },
        {
          "name": "spring-boot-gradle-plugin-3.0.6.jar",
          "url": "spring-boot-gradle-plugin-3.0.6.jar",
          "size": 137490,
          "sha512": "17bd04e8e018b2eb03c584ea39f5dc1a08cb64723e9abca6c9eed2e6e2b554aa4267f923440ff37f361fea178b021cfe53b725d67d3b6139f38e300b4bef0a65",
          "sha256": "b4e5bef914a220c1af37e7b5d957481125237e47fd83e91309740fb0c018351d",
          "sha1": "2ddef8d6a039aa16d3a59949ad784d541baa7d72",
          "md5": "7c1e60f06f907c9ae31b18bd2344cc07"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-gradle-plugin-maven-optional",
          "version": "3.0.6"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-gradle-plugin-3.0.6.jar",
          "url": "spring-boot-gradle-plugin-3.0.6.jar",
          "size": 137490,
          "sha512": "17bd04e8e018b2eb03c584ea39f5dc1a08cb64723e9abca6c9eed2e6e2b554aa4267f923440ff37f361fea178b021cfe53b725d67d3b6139f38e300b4bef0a65",
          "sha256": "b4e5bef914a220c1af37e7b5d957481125237e47fd83e91309740fb0c018351d",
          "sha1": "2ddef8d6a039aa16d3a59949ad784d541baa7d72",
          "md5": "7c1e60f06f907c9ae31b18bd2344cc07"
        },
        {
          "name": "spring-boot-gradle-plugin-3.0.6.jar",
          "url": "spring-boot-gradle-plugin-3.0.6.jar",
          "size": 137490,
          "sha512": "17bd04e8e018b2eb03c584ea39f5dc1a08cb64723e9abca6c9eed2e6e2b554aa4267f923440ff37f361fea178b021cfe53b725d67d3b6139f38e300b4bef0a65",
          "sha256": "b4e5bef914a220c1af37e7b5d957481125237e47fd83e91309740fb0c018351d",
          "sha1": "2ddef8d6a039aa16d3a59949ad784d541baa7d72",
          "md5": "7c1e60f06f907c9ae31b18bd2344cc07"
        },
        {
          "name": "spring-boot-gradle-plugin-3.0.6.jar",
          "url": "spring-boot-gradle-plugin-3.0.6.jar",
          "size": 137490,
          "sha512": "17bd04e8e018b2eb03c584ea39f5dc1a08cb64723e9abca6c9eed2e6e2b554aa4267f923440ff37f361fea178b021cfe53b725d67d3b6139f38e300b4bef0a65",
          "sha256": "b4e5bef914a220c1af37e7b5d957481125237e47fd83e91309740fb0c018351d",
          "sha1": "2ddef8d6a039aa16d3a59949ad784d541baa7d72",
          "md5": "7c1e60f06f907c9ae31b18bd2344cc07"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-gradle-plugin-maven-optional",
          "version": "3.0.6"
        }
      ]
    }
  ]
}
