{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "3.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.8"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.8"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.8"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.0.6.jar",
          "url": "spring-boot-starter-tomcat-3.0.6.jar",
          "size": 4793,
          "sha512": "e0f193eb94c25d390679f0f1fe737c2d60c46b5d283f19f0ea944646ce07b1fa70db9e1ff3146f664e7d5c908873468cca8701c0569b6492a56c4e49239fd850",
          "sha256": "8a33faf8e68cd2d150527144658d13b065b2158b82de343fca0e45bc105524e4",
          "sha1": "feae12210905b6cb7ce8affce4f309665c4a805b",
          "md5": "382a9b0b94d0eab9761710c76f71492d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "10.1.8"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "10.1.8"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "10.1.8"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.0.6.jar",
          "url": "spring-boot-starter-tomcat-3.0.6.jar",
          "size": 4793,
          "sha512": "e0f193eb94c25d390679f0f1fe737c2d60c46b5d283f19f0ea944646ce07b1fa70db9e1ff3146f664e7d5c908873468cca8701c0569b6492a56c4e49239fd850",
          "sha256": "8a33faf8e68cd2d150527144658d13b065b2158b82de343fca0e45bc105524e4",
          "sha1": "feae12210905b6cb7ce8affce4f309665c4a805b",
          "md5": "382a9b0b94d0eab9761710c76f71492d"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.0.6.jar",
          "url": "spring-boot-starter-tomcat-3.0.6.jar",
          "size": 4793,
          "sha512": "e0f193eb94c25d390679f0f1fe737c2d60c46b5d283f19f0ea944646ce07b1fa70db9e1ff3146f664e7d5c908873468cca8701c0569b6492a56c4e49239fd850",
          "sha256": "8a33faf8e68cd2d150527144658d13b065b2158b82de343fca0e45bc105524e4",
          "sha1": "feae12210905b6cb7ce8affce4f309665c4a805b",
          "md5": "382a9b0b94d0eab9761710c76f71492d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "3.0.6"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.0.6.jar",
          "url": "spring-boot-starter-tomcat-3.0.6.jar",
          "size": 4793,
          "sha512": "e0f193eb94c25d390679f0f1fe737c2d60c46b5d283f19f0ea944646ce07b1fa70db9e1ff3146f664e7d5c908873468cca8701c0569b6492a56c4e49239fd850",
          "sha256": "8a33faf8e68cd2d150527144658d13b065b2158b82de343fca0e45bc105524e4",
          "sha1": "feae12210905b6cb7ce8affce4f309665c4a805b",
          "md5": "382a9b0b94d0eab9761710c76f71492d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "3.0.6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.0.6-javadoc.jar",
          "url": "spring-boot-starter-tomcat-3.0.6-javadoc.jar",
          "size": 4743,
          "sha512": "87aa4a71703332f449db3d20fd7506d0019131a0408f08f194f8117812ad35b0d0531788d3fca8d13f56d8dd9366d5fa7ba1b78d6696e09d12509824acbd54ed",
          "sha256": "678bfd2b01b83a7026331abd8d0a81e3f77d1b9261c4293d8dd4685b596a8210",
          "sha1": "59efe2aac9a6c7ce49c1d54eb6fb6c286eb131a1",
          "md5": "4cc24c675c5eb9f3f586092e2375e4bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-3.0.6-sources.jar",
          "url": "spring-boot-starter-tomcat-3.0.6-sources.jar",
          "size": 4741,
          "sha512": "8d238b1522a04c70dfd04d76e07fcc5b5cb73e5a9ef073f64f8bb7cffedad8e06662b3cf2f144c02454f8d24cbdbd6184b51fa77a37c78593e980a178b143a64",
          "sha256": "92b8ae8a9ff9a1f2a8a52b4cccfa79675bb905ca0f285847f903005f9f3825ee",
          "sha1": "744836dad2cb46f349d760598126c34d48fe6153",
          "md5": "b34f7b181221956ff4c5543c376063be"
        }
      ]
    }
  ]
}
