{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "3.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.8"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.33"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.0.6.jar",
          "url": "spring-boot-starter-3.0.6.jar",
          "size": 4768,
          "sha512": "6d5a2790a24bc162d6be55b2d3a3f292da5e3717d45a6cd5ccf703c44fac186b88c62858ff17ac9fd9711520b180dde4664b7b1fddb793b50d8a27a2c8a59d3f",
          "sha256": "99d7106538c1b6790aca72f9d99a3fcb2880cb9f3a63426730c8805e893b7370",
          "sha1": "01029c155da41fa04820cf81fdbe5752260eead5",
          "md5": "899e0bc24739ec6716c9e8baa0e4f853"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.8"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.33"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-3.0.6.jar",
          "url": "spring-boot-starter-3.0.6.jar",
          "size": 4768,
          "sha512": "6d5a2790a24bc162d6be55b2d3a3f292da5e3717d45a6cd5ccf703c44fac186b88c62858ff17ac9fd9711520b180dde4664b7b1fddb793b50d8a27a2c8a59d3f",
          "sha256": "99d7106538c1b6790aca72f9d99a3fcb2880cb9f3a63426730c8805e893b7370",
          "sha1": "01029c155da41fa04820cf81fdbe5752260eead5",
          "md5": "899e0bc24739ec6716c9e8baa0e4f853"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.0.6.jar",
          "url": "spring-boot-starter-3.0.6.jar",
          "size": 4768,
          "sha512": "6d5a2790a24bc162d6be55b2d3a3f292da5e3717d45a6cd5ccf703c44fac186b88c62858ff17ac9fd9711520b180dde4664b7b1fddb793b50d8a27a2c8a59d3f",
          "sha256": "99d7106538c1b6790aca72f9d99a3fcb2880cb9f3a63426730c8805e893b7370",
          "sha1": "01029c155da41fa04820cf81fdbe5752260eead5",
          "md5": "899e0bc24739ec6716c9e8baa0e4f853"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "3.0.6"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.0.6.jar",
          "url": "spring-boot-starter-3.0.6.jar",
          "size": 4768,
          "sha512": "6d5a2790a24bc162d6be55b2d3a3f292da5e3717d45a6cd5ccf703c44fac186b88c62858ff17ac9fd9711520b180dde4664b7b1fddb793b50d8a27a2c8a59d3f",
          "sha256": "99d7106538c1b6790aca72f9d99a3fcb2880cb9f3a63426730c8805e893b7370",
          "sha1": "01029c155da41fa04820cf81fdbe5752260eead5",
          "md5": "899e0bc24739ec6716c9e8baa0e4f853"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "3.0.6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.0.6-javadoc.jar",
          "url": "spring-boot-starter-3.0.6-javadoc.jar",
          "size": 4734,
          "sha512": "84c265db204b7ede6d6edd55e388ced5cf273d58a79661f8cb3d55076b7ed269ecc59a10569aa89d67105c83074902697a0ef323031adc73ccdf31b4a83be26e",
          "sha256": "a686bcc5baecaaa6dd3a980675ecbe0a0c55bc4d9ff7e6e011f85e5d64288045",
          "sha1": "1decfbce7bfe11efc74d30f6792516c5123f0c63",
          "md5": "cd3829afedb146a0bd58a8c2f5a86435"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-3.0.6-sources.jar",
          "url": "spring-boot-starter-3.0.6-sources.jar",
          "size": 4734,
          "sha512": "27f06f6095ffe3f43575ad5f19d45831da348bfd93d58b71348dab780f3abfe4bce2abc28f301af576b993d85507039bc9531da92e149a98441cdfd75bbee88e",
          "sha256": "76f81bb2d687e1c6846b84fb560a293fd4544b9d6a140e8b82cdf2a633abfbdd",
          "sha1": "5e00b3476205b7e50e62d6b6b18c29084f75e898",
          "md5": "8cc15ac369bac236fcfc9bb1e9e4a5d5"
        }
      ]
    }
  ]
}
