{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context",
    "version": "6.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-6.0.8.jar",
          "url": "spring-context-6.0.8.jar",
          "size": 1182789,
          "sha512": "8181241cb6fe46bec208f103c14237455736d6b85e97eb7096e45bd82a1122dc7bf4ea880132469c47aa539f94894b5982334d77482748f024efb2c12d5f3c61",
          "sha256": "c7b3ef726d04c4b8325412ecf4d99e1f928b23892be7a4cb2084cc2da70b1749",
          "sha1": "4550c5e2bbb8cd07647b1b29b47c73cf4732de8c",
          "md5": "1450c8091e8adcc48797932367268354"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-6.0.8.jar",
          "url": "spring-context-6.0.8.jar",
          "size": 1182789,
          "sha512": "8181241cb6fe46bec208f103c14237455736d6b85e97eb7096e45bd82a1122dc7bf4ea880132469c47aa539f94894b5982334d77482748f024efb2c12d5f3c61",
          "sha256": "c7b3ef726d04c4b8325412ecf4d99e1f928b23892be7a4cb2084cc2da70b1749",
          "sha1": "4550c5e2bbb8cd07647b1b29b47c73cf4732de8c",
          "md5": "1450c8091e8adcc48797932367268354"
        }
      ]
    }
  ]
}
