{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-thymeleaf",
    "version": "2.7.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf-spring5",
          "version": {
            "requires": "3.0.15.RELEASE"
          }
        },
        {
          "group": "org.thymeleaf.extras",
          "module": "thymeleaf-extras-java8time",
          "version": {
            "requires": "3.0.4.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-2.7.4.jar",
          "url": "spring-boot-starter-thymeleaf-2.7.4.jar",
          "size": 4770,
          "sha512": "5051876d51bf0eb63bdc6730d8fb103a654d7a7b5de0e3f6533e134bb4aac36094e5186bb244681dcafe0c46480efa22215fe16356cb0e3e2d70e11e9ed687c2",
          "sha256": "741e333aa15705396e77fccfcd3d74ab05c1c2ce6d459a8cd00b3a9cf9108e6e",
          "sha1": "d2d8bd4b3660ca87b6237db95486f714a0b82bc8",
          "md5": "532fbfed9a1bb6a6176de72017c67bec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "2.7.4"
          }
        },
        {
          "group": "org.thymeleaf",
          "module": "thymeleaf-spring5",
          "version": {
            "requires": "3.0.15.RELEASE"
          }
        },
        {
          "group": "org.thymeleaf.extras",
          "module": "thymeleaf-extras-java8time",
          "version": {
            "requires": "3.0.4.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-2.7.4.jar",
          "url": "spring-boot-starter-thymeleaf-2.7.4.jar",
          "size": 4770,
          "sha512": "5051876d51bf0eb63bdc6730d8fb103a654d7a7b5de0e3f6533e134bb4aac36094e5186bb244681dcafe0c46480efa22215fe16356cb0e3e2d70e11e9ed687c2",
          "sha256": "741e333aa15705396e77fccfcd3d74ab05c1c2ce6d459a8cd00b3a9cf9108e6e",
          "sha1": "d2d8bd4b3660ca87b6237db95486f714a0b82bc8",
          "md5": "532fbfed9a1bb6a6176de72017c67bec"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-2.7.4.jar",
          "url": "spring-boot-starter-thymeleaf-2.7.4.jar",
          "size": 4770,
          "sha512": "5051876d51bf0eb63bdc6730d8fb103a654d7a7b5de0e3f6533e134bb4aac36094e5186bb244681dcafe0c46480efa22215fe16356cb0e3e2d70e11e9ed687c2",
          "sha256": "741e333aa15705396e77fccfcd3d74ab05c1c2ce6d459a8cd00b3a9cf9108e6e",
          "sha1": "d2d8bd4b3660ca87b6237db95486f714a0b82bc8",
          "md5": "532fbfed9a1bb6a6176de72017c67bec"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-thymeleaf-maven-optional",
          "version": "2.7.4"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-2.7.4.jar",
          "url": "spring-boot-starter-thymeleaf-2.7.4.jar",
          "size": 4770,
          "sha512": "5051876d51bf0eb63bdc6730d8fb103a654d7a7b5de0e3f6533e134bb4aac36094e5186bb244681dcafe0c46480efa22215fe16356cb0e3e2d70e11e9ed687c2",
          "sha256": "741e333aa15705396e77fccfcd3d74ab05c1c2ce6d459a8cd00b3a9cf9108e6e",
          "sha1": "d2d8bd4b3660ca87b6237db95486f714a0b82bc8",
          "md5": "532fbfed9a1bb6a6176de72017c67bec"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-thymeleaf-maven-optional",
          "version": "2.7.4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-2.7.4-javadoc.jar",
          "url": "spring-boot-starter-thymeleaf-2.7.4-javadoc.jar",
          "size": 4747,
          "sha512": "60f4582f7bbf06877055b7f9042901eabc20595357a0a092c3194210268594746e805ef47f17c24760cf07966861567b6339077f26de4bea8c8439a3b4ef67cd",
          "sha256": "21fa5c79ad791c49b00692fdda7e535eae0f589a23f45f9821a3089c685f6400",
          "sha1": "5d27bfb45b6078ad4f1b6412e873e52c47981820",
          "md5": "1068d370e48f14213cecaffb369a7b6f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-thymeleaf-2.7.4-sources.jar",
          "url": "spring-boot-starter-thymeleaf-2.7.4-sources.jar",
          "size": 4746,
          "sha512": "8a0023b221992c98880d2294a1342905b818d8fed5a19335112ae0c63a3fb2701fb015b38d384cf3906d7f4fee65c623077b566b91540199d57204fca3a40f75",
          "sha256": "cc570b7a309ef0bedd02e2add2dfb9f5b9ec3645b5fc1a2e16fe4dc5a976d32a",
          "sha1": "957a38930c5c536ab8e54d6f8f400ec43c333f72",
          "md5": "77591b045f156eb71e0d864b82d36c73"
        }
      ]
    }
  ]
}
