{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-json",
    "version": "3.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.0.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.0.6.jar",
          "url": "spring-boot-starter-json-3.0.6.jar",
          "size": 4747,
          "sha512": "a728091b6558cfba381f73c5eb9da282cc26f7ba0e2b5d3df9c0971b59c6f83dba2f0300d0a80bd6c8fcf28b64c2836640eca8c74f848b409c09137827e06b54",
          "sha256": "6b98b8767aedcf3ff23872675c0d6a68b12162da45529a08b362ed1a18a2b8b3",
          "sha1": "e0a1dd1653750a8e0a25b7b6be977231d7fa607e",
          "md5": "7bd2e626d41ddd6ec7a170dd2d609617"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.0.6"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.0.8"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jdk8",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.datatype",
          "module": "jackson-datatype-jsr310",
          "version": {
            "requires": "2.14.2"
          }
        },
        {
          "group": "com.fasterxml.jackson.module",
          "module": "jackson-module-parameter-names",
          "version": {
            "requires": "2.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-json-3.0.6.jar",
          "url": "spring-boot-starter-json-3.0.6.jar",
          "size": 4747,
          "sha512": "a728091b6558cfba381f73c5eb9da282cc26f7ba0e2b5d3df9c0971b59c6f83dba2f0300d0a80bd6c8fcf28b64c2836640eca8c74f848b409c09137827e06b54",
          "sha256": "6b98b8767aedcf3ff23872675c0d6a68b12162da45529a08b362ed1a18a2b8b3",
          "sha1": "e0a1dd1653750a8e0a25b7b6be977231d7fa607e",
          "md5": "7bd2e626d41ddd6ec7a170dd2d609617"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.0.6.jar",
          "url": "spring-boot-starter-json-3.0.6.jar",
          "size": 4747,
          "sha512": "a728091b6558cfba381f73c5eb9da282cc26f7ba0e2b5d3df9c0971b59c6f83dba2f0300d0a80bd6c8fcf28b64c2836640eca8c74f848b409c09137827e06b54",
          "sha256": "6b98b8767aedcf3ff23872675c0d6a68b12162da45529a08b362ed1a18a2b8b3",
          "sha1": "e0a1dd1653750a8e0a25b7b6be977231d7fa607e",
          "md5": "7bd2e626d41ddd6ec7a170dd2d609617"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-json-maven-optional",
          "version": "3.0.6"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.0.6.jar",
          "url": "spring-boot-starter-json-3.0.6.jar",
          "size": 4747,
          "sha512": "a728091b6558cfba381f73c5eb9da282cc26f7ba0e2b5d3df9c0971b59c6f83dba2f0300d0a80bd6c8fcf28b64c2836640eca8c74f848b409c09137827e06b54",
          "sha256": "6b98b8767aedcf3ff23872675c0d6a68b12162da45529a08b362ed1a18a2b8b3",
          "sha1": "e0a1dd1653750a8e0a25b7b6be977231d7fa607e",
          "md5": "7bd2e626d41ddd6ec7a170dd2d609617"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-json-maven-optional",
          "version": "3.0.6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.0.6-javadoc.jar",
          "url": "spring-boot-starter-json-3.0.6-javadoc.jar",
          "size": 4742,
          "sha512": "0ad535ebcbf276c1e642f340a52da88d105b2c42b1108de6f904f36c1ddf42b645b5867bb7c1cbbb63c8aaf920d2439be127a77661df91619adf5ccafd13c02a",
          "sha256": "6def47cd8706b9e8ea24cf997793dcf05cd359f6ed2299a41199f6c7fdcb05e3",
          "sha1": "9583e9233cbc08df146650c06ed012b48a0fe748",
          "md5": "6850c756c6bab7077f3b180ce16c4545"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-json-3.0.6-sources.jar",
          "url": "spring-boot-starter-json-3.0.6-sources.jar",
          "size": 4741,
          "sha512": "ed708a9a1991dd2829177765e19c3bdc875e2086092073f208fe6244496e1be0da741e108f6aa26240fbcdf1471f28ed47accd5a8ccfbcef7baf2fd6f5192fbb",
          "sha256": "eb1af2da6f6b9a50edfd8bc02bc34b4e05a2dff4f0a8ab80af07c36865a2902a",
          "sha1": "96d8c328860107a77fa2f77d131488e66cc632de",
          "md5": "4c1f1d9eaf73f0aad4df4676af29cebe"
        }
      ]
    }
  ]
}
