{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-test",
    "version": "3.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.0.6.jar",
          "url": "spring-boot-test-3.0.6.jar",
          "size": 246038,
          "sha512": "706bc17f5b4c20da5d71f91048b1443aec99e67d801f2a3bb4277ba56b152ea08df2128d64f938807e3f8bf7cd154fe58009a341c91607a6a6ff7ef34632f15b",
          "sha256": "b733ae27d04eaf65ae13e008474edc184d78113599a02f20d3e1274a9a68e053",
          "sha1": "2d29691a65f09c09be90f1c1ea8813fa56a76e2b",
          "md5": "e03d9ac892864cbc0dff86bfbff3e702"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "3.0.6"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-test-3.0.6.jar",
          "url": "spring-boot-test-3.0.6.jar",
          "size": 246038,
          "sha512": "706bc17f5b4c20da5d71f91048b1443aec99e67d801f2a3bb4277ba56b152ea08df2128d64f938807e3f8bf7cd154fe58009a341c91607a6a6ff7ef34632f15b",
          "sha256": "b733ae27d04eaf65ae13e008474edc184d78113599a02f20d3e1274a9a68e053",
          "sha1": "2d29691a65f09c09be90f1c1ea8813fa56a76e2b",
          "md5": "e03d9ac892864cbc0dff86bfbff3e702"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.0.6-javadoc.jar",
          "url": "spring-boot-test-3.0.6-javadoc.jar",
          "size": 412562,
          "sha512": "e34bbaf3b156736cea6252c529ebb418b7d3d61aeb111ded13d3acc05f541a05535104a72eb0afe8e55fff93ec0a1c86321bfc22d03071be97ca3f4b7a83d4cb",
          "sha256": "cc8edf7119ae98f63bf82ed4b54b9ccdb91fee3ca10756de622d3769eddda326",
          "sha1": "c1ceaf39978593034d59297251766269348a2e3f",
          "md5": "9c2d2215975816be538705c5561f0d11"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.0.6-sources.jar",
          "url": "spring-boot-test-3.0.6-sources.jar",
          "size": 166152,
          "sha512": "3906d2623805e05d4486144f91c9d6b054c97927e33692d74fbe64ad2a5237b48d0990fe90042bea7c107844667ca0f37d86264718265797e4c7f1397e0b9a7c",
          "sha256": "76bf2cd7ed9db27bcedf8ca0e0fc3f1b8bbbb9d6d75f87343c509fc6edc09ac4",
          "sha1": "b129a3b15c761df5b8d35eb538addd7ebd50dbef",
          "md5": "04512db5581a743896600e87bad2150c"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-test-3.0.6.jar",
          "url": "spring-boot-test-3.0.6.jar",
          "size": 246038,
          "sha512": "706bc17f5b4c20da5d71f91048b1443aec99e67d801f2a3bb4277ba56b152ea08df2128d64f938807e3f8bf7cd154fe58009a341c91607a6a6ff7ef34632f15b",
          "sha256": "b733ae27d04eaf65ae13e008474edc184d78113599a02f20d3e1274a9a68e053",
          "sha1": "2d29691a65f09c09be90f1c1ea8813fa56a76e2b",
          "md5": "e03d9ac892864cbc0dff86bfbff3e702"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-maven-optional",
          "version": "3.0.6"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-test-3.0.6.jar",
          "url": "spring-boot-test-3.0.6.jar",
          "size": 246038,
          "sha512": "706bc17f5b4c20da5d71f91048b1443aec99e67d801f2a3bb4277ba56b152ea08df2128d64f938807e3f8bf7cd154fe58009a341c91607a6a6ff7ef34632f15b",
          "sha256": "b733ae27d04eaf65ae13e008474edc184d78113599a02f20d3e1274a9a68e053",
          "sha1": "2d29691a65f09c09be90f1c1ea8813fa56a76e2b",
          "md5": "e03d9ac892864cbc0dff86bfbff3e702"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-test-maven-optional",
          "version": "3.0.6"
        }
      ]
    }
  ]
}
