{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot",
    "version": "3.0.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.0.6.jar",
          "url": "spring-boot-3.0.6.jar",
          "size": 1485430,
          "sha512": "42f1b651ad90304aa35dd43c2d37d12cfa7e2266bc3006bccb24b0bedfe9684440df62714ad40083a128b6572649ab8cca670018b4d6f83935fef81dc271710f",
          "sha256": "b51782c26182b59abcb108aa5e7113865b9e9ec304afe13f5374cfad54a50dce",
          "sha1": "095ac2c7aa28fcdef587b2c4f554016f8b9af624",
          "md5": "27e9c460383b354a362e74f786a77eec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.0.8"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-3.0.6.jar",
          "url": "spring-boot-3.0.6.jar",
          "size": 1485430,
          "sha512": "42f1b651ad90304aa35dd43c2d37d12cfa7e2266bc3006bccb24b0bedfe9684440df62714ad40083a128b6572649ab8cca670018b4d6f83935fef81dc271710f",
          "sha256": "b51782c26182b59abcb108aa5e7113865b9e9ec304afe13f5374cfad54a50dce",
          "sha1": "095ac2c7aa28fcdef587b2c4f554016f8b9af624",
          "md5": "27e9c460383b354a362e74f786a77eec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.0.6-javadoc.jar",
          "url": "spring-boot-3.0.6-javadoc.jar",
          "size": 2152791,
          "sha512": "818a559a3df627a2d58f40f2cf17f458b3b4cd70dc9ce04194b01e51221647d4121ac7211ed250d12b6f6d44097c0598ac7330bfe8131e22c693ad6007086d2b",
          "sha256": "7700d16167ee4b1843bc5fde4735325b79f837f2c45f951d7c141c186827a92d",
          "sha1": "afe41bbb8dce1d3df1d6421de739677aa2e224f9",
          "md5": "6308f38e3158ea8987084420a2bd60f0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.0.6-sources.jar",
          "url": "spring-boot-3.0.6-sources.jar",
          "size": 1035486,
          "sha512": "340889487c397d9c08134afa736f70c5bcb606e572da1a1087692fd9c91b852e7e5e2a3ea1a2ba85c505dcf2f331d7159a8770af64f8b276a65932e2661c8e84",
          "sha256": "6efb34c5bdf9c47e053c76fce202f60105c37101b7aa73c48b2dc84d13f34d54",
          "sha1": "d53375eb837b5e04125ad8f6ce317b9a5a1d1302",
          "md5": "ca792452ca803daf29d7b5334175ab10"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-3.0.6.jar",
          "url": "spring-boot-3.0.6.jar",
          "size": 1485430,
          "sha512": "42f1b651ad90304aa35dd43c2d37d12cfa7e2266bc3006bccb24b0bedfe9684440df62714ad40083a128b6572649ab8cca670018b4d6f83935fef81dc271710f",
          "sha256": "b51782c26182b59abcb108aa5e7113865b9e9ec304afe13f5374cfad54a50dce",
          "sha1": "095ac2c7aa28fcdef587b2c4f554016f8b9af624",
          "md5": "27e9c460383b354a362e74f786a77eec"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-maven-optional",
          "version": "3.0.6"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-3.0.6.jar",
          "url": "spring-boot-3.0.6.jar",
          "size": 1485430,
          "sha512": "42f1b651ad90304aa35dd43c2d37d12cfa7e2266bc3006bccb24b0bedfe9684440df62714ad40083a128b6572649ab8cca670018b4d6f83935fef81dc271710f",
          "sha256": "b51782c26182b59abcb108aa5e7113865b9e9ec304afe13f5374cfad54a50dce",
          "sha1": "095ac2c7aa28fcdef587b2c4f554016f8b9af624",
          "md5": "27e9c460383b354a362e74f786a77eec"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-maven-optional",
          "version": "3.0.6"
        }
      ]
    }
  ]
}
